### ISSUE TITLE
chosen-container getting width: 0px

### ISSUE THREAD

**Issue by gandarez** [harvesthq/chosen#1548]
I've the latest version of chose (1.0.0) and I'm getting width: 0px within chosen-container. I have no idea why the function this.container_width() has been returning "0px". Someone could help me?

note: I'm using inside a bootstrap modal which shows on the fly
note2: I must call modal() and then call chosen() to not get fail

**Comment by zalza13** [comment]
In ths code of  "chosen.jquery.js" look:

  container_props = {
        'class': container_classes.join(' '),
        'style': **"width: " + (this.container_width()) **+ ";",
        'title': this.form_field.title
      };

Then simply do:

   $("#idControl").chosen({
        width: "250px"
    });

**Comment by chrisjefferies** [comment]
I realize this is a bit old, but I've come up with a marginally better solution (for 1.7.0) by adding the following function:

```javascript
function defModalWidth(obj) {
  if (obj.container_width() == 0) {
    return 600;    
  } else {
    return obj.container_width();
  }
}```

and replacing `this.container_width()` in `set_up_html` by calling it thusly: 

```javascript
this.container.width(defModalWidth(this));
```

Anything that chosen thinks should be zero because the modal it's in is hidden will get 600 instead.

Seems to work.

**Comment by chrisjefferies** [comment]
I realize this is a bit old, but I've come up with a marginally better solution (for 1.7.0) by adding the following function:

```javascript
function defModalWidth(obj) {
  if (obj.container_width() == '0px') {
    return '600px';    
  } else {
    return obj.container_width();
  }
}
```

and replacing `this.container_width()` in `set_up_html` by calling it thusly:

```javascript
this.container.width(defModalWidth(this));
```

Anything that chosen thinks should be zero because the modal it's in is hidden will get 600 instead.

Seems to work.
