### ISSUE TITLE
Problem with tab stops and navigating the form by pressing tab

### ISSUE THREAD

**Issue by aziz** [harvesthq/chosen#169]
I've some weird problems that are driving me crazy and all of them involve tab navigation on the form. 

The first one I can replicate on the example.html file (from chosen repo). in Firefox the single chosen select will never get focus if you navigate using tabs! I really don't know how to fix it! 

The second one is not happening on the example.html but it happens in my test application. the problem is that close buttons on selected items in multiple chosen select widget with get the focus. so if you have three selected items in select you need to press four tabs to get into the input! you can see it in the image below 

![screenshot](http://f.cl.ly/items/3i183K0a2Q053o1G133M/Screen%20Shot%202011-08-08%20at%2011.04.43%20PM.png)

it happens in both firefox and chrome and the solution is to add tabindex="-1" to all the links that generated by chosen.

UPDATE 1:  more on this issue
I confirmed that adding tabindex="-1" to generated close links will fix the multi select issue.
Another issue with single select on my test app is that it need 2 tab pressed to pass it. I thing it's because the search input (although hidden) will need an extra tab to pass. 
I think some of these issues does happen on the example.html cause the tab indexes are defined explicitly.

**Comment by Giovani-Brady** [comment]
REOPEN THE FOLLOWING RELATED ISSUE #244

**Comment by Giovani-Brady** [comment]
@pfiller created a form with input and select elements that have explicit tab indexes set. Using chosen, the select form fields are skipped over when tabbing through the form fields. (this is because of the overriding done by chosen to set the tabindex="-1" for all select fields targeted.

Why is this intentional behavior?
Why not detect if the targeted element has a tabindex set and use that in the new container generated with chosen?

reopen #244 

(we can only hide from our problems, never rid ourselves of them by running)

**Comment by janbaykara** [comment]
This is still a problem, as far as I can tell.

**Comment by ninboy** [comment]
There's still issues when navigating the forms using the Tab key. I'm trying to isolate the offending code, but the problem it's there even in Chosen 1.5.1

**Comment by koenpunt** [comment]
So summarize the original issue:

- in Firefox the single chosen select will never get focus if you navigate using tabs  
  **can't reproduce**

- close buttons on selected items in multiple chosen select widget with get the focus  
  **can't reproduce**

- Another issue with single select on my test app is that it need 2 tab pressed to pass it.  
  **can't reproduce**

@ninboy @janbaykara since you both are the last to comment here; is there still an issue with Chosen? If so, on which OS and which browsers does it exist?
