### ISSUE TITLE
allow_single_deselect doesn't work on dynamic updated select

### ISSUE THREAD

**Issue by xflash** [harvesthq/chosen#1780]
allow_single_deselect doesn't work after updating dynamicaly a select.
Even after triggering a "chosen:updated" event 

Fiddle : http://jsfiddle.net/wcCfL/

**Comment by jamesgbc** [comment]
Even when you prepopulate the base select with an empty option and the initial value option (required in a form scenario so you can set the initial value) then add dynamic options later, the behaviour is still buggy because clearing the selection sets the empty option as selected, but does not remove selected from the initially set option.  The single select then has 2 options selected and if saved as part of a form, it will not return the empty option.  This means the plugin does not support the use scenario of having dynamically populated selects on a form with the ability to clear the entry.

**Comment by dmarra** [comment]
I can confirm this still does not work correctly. Even if I dynamically add an empty option to the select, and update it, it still does not respect this option. VERY frustrating.
