### ISSUE TITLE
Closing multiple mode chosen on click

### ISSUE THREAD

**Issue by thorhallur** [harvesthq/chosen#1810]
On single-mode chosen when you click the control the list opens and when you click the control (not the list) again it closes, as expected.  But in multiple-mode when I do the same thing the list stays open.  Is there a way for me to close the list in multiple mode when the user clicks on the control itself?  (I'm able to do some customization in the plugin for myself but I'm having issues with this one as the control behaves differently to clicks depending on whether the control has focus or not. I edited the choices_click function and asked the control to hide_results if results_showing = true, which works fine when the control has focus but doesn't work when it doesn't. In that case the results flickers (shows and hides quickly) )

**Comment by pfiller** [comment]
When you click the top part of a single chosen, you are specifically removing focus from the search field. That's why the control closes and why it makes sense for the control to close.

When you click the top part of a multiple chosen, you are clicking the search box. When you focus the search box in any version of Chosen, the correct behavior is to start showing the search results. That's why it doesn't make sense to close the dropdown on a second click.

Hope that made some sense. This thread is now 2+ years old, so I'm guessing you don't care any longer 😝
