### ISSUE TITLE
options in multiple select list don't respond to mouseenter jquery event

### ISSUE THREAD

**Issue by themysteriouscitiesofgold** [harvesthq/chosen#1819]
I am using the multiple select with groups menu (multiple tabindex="6") from the chosen index page to create a select list of shapes that need a visual representation. my idea was to highlight a corresponding image (the group of images are right beside or under the menu) whenever i hover over an option in the list, by giving the image a border color of red. the code i came up with works with regular select menus, but it does not work with your plugin(nothing happens when i hover over the options). 
I looked at the console and there are no errors listed. 
here is my code for the hover effect:
 css:

```css
.hover{border:4px solid red}
```

JQuery:

```javascript
$(document).ready(function() {

  var C = $("#a20 option");  //"a20" is the id for the select menu
  C.mouseenter(function(){		    
    var V = $(this).val();            //for example, the option value="round"
    $("#"+V).addClass("hover");   //add class to the img with id="round"
  });
   
  C.mouseleave(function(){
    var V = $(this).val();
    $("#"+V).removeClass("hover");
  }); 
});
```

here is an example of this code working with a regular select list: http://jsfiddle.net/MhmC7/

how else could i create this effect with your plugin?  thank you. I'm using firefox and windows 7.

**Comment by pfiller** [comment]
This issue is well over 2 years old so I'm going to assume you no need help ... 

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
