### ISSUE TITLE
Search doesn't work when whitespaces before/after text in <option> field

### ISSUE THREAD

**Issue by mpiasta-ca** [harvesthq/chosen#184]
When I write HTML, I have tendency of putting code on a new line.

```html
<option id="100">
	United States
</option>
```

With Chosen, if there are tabs, line-breaks, or spaces between the ``<option></option>``, suddenly the search no longer finds the results. For example, a search for U would be unable to see 'United States' in this scenario.

**Comment by Hilgo** [comment]
it's been a while since this was closed but i faced this same situation, i made a simple [jsfiddle](https://jsfiddle.net/vopcexLm/11/) to demonstrate.

Tested with the latest chosen version i could find in [cdnjs](https://cdnjs.com/libraries/chosen) (1.4.2) and jquery 2.0.3 and browsers: Chrome v.49, Firefox v45, IE v11 on windows 8.1.

The option with whitespaces in html markup only shows up when you type the spaces as well, with or without the property `search_contains: true`.

Should we remove white spaces and break lines before initializing chosen?

**Comment by pfiller** [comment]
Having spaces in the middle of a word is an interesting problem. To fix that problem, Chosen would have to split each option string and trim them before putting them back together. That's a fairly complex solution (and potentially computationally expensive in large lists) for something that is avoidable by not having those spaces in the first place.

> Should we remove white spaces and break lines before initializing chosen?

I guess my answer is probably "yes". Removing the white space in the middle of words is probably the easiest of all possible solutions.
