### ISSUE TITLE
Flickering when the page is laoding.

### ISSUE THREAD

**Issue by praveenlobo7** [harvesthq/chosen#1840]
When we are loading a page, we see dropdown first and den after a while it changes to chosen textbox.

**Comment by rossjones** [comment]
I encountered this problem today when using Chosen 1.4.2 and JQuery 1.12.2 when there is a Google Analytics block in the code.

You can see the problem in action at https://jsfiddle.net/rossjones/dy29db6w/5/

It is however easily solved by wrapping the GA block inside a ```window.onload = function(){ .... }``` , rather than a $(document).ready()

This is just in case someone else encounters flicker with Chosen when GA is installed, no action requested as there is a fix above :)
