### ISSUE TITLE
Extended Mobile Browser detection

### ISSUE THREAD

**Issue by StephKoenig** [harvesthq/chosen#1848]
I added support  for detecting Windows Mobile, older IEMobile, BB10 and older BlackBerrys on my local version of 1.1.0 using the following code snippet - I had to move the IE detection to the bottom, hope this helps

```Javascript
AbstractChosen.browser_is_supported = function() {
  if (/iP(od|hone)/i.test(navigator.userAgent)) {
    return false;
  }
  if (/Android/i.test(navigator.userAgent)) {
    if (/Mobile/i.test(navigator.userAgent)) {
      return false;
    }
  }
  if (/IEMobile/i.test(navigator.userAgent)) {
          return false;
  }
  if (/Windows Phone/i.test(navigator.userAgent)) {
          return false;
  }
  if (/BlackBerry/i.test(navigator.userAgent)) {
    return false;
  }
  if (/BB10/i.test(navigator.userAgent)) {
    return false;
  }
  if (window.navigator.appName === "Microsoft Internet Explorer") {
    return document.documentMode >= 8;
  }
  return true;
};
```

Also we found in our testing of multiple phones and OSs that not all properties of the window object are available but accessing properties of navigator works fine which is odd because they're the same (or should be) and window.navigator is more precise/explicit...

**Comment by tremby** [comment]
@StephKoenig, see https://github.com/harvesthq/chosen/issues/2439. I don't want to just copy and paste your code for my own PR; maybe you can?

**Comment by tjschuck** [comment]
@tremby I appreciate your respect for authorship here!

Just two notes, though, since this is an old issue, and @StephKoenig might have moved on:

1. Per our contributing document, submitted patches are also covered by our MIT license, so you can freely use the code here if you'd like.

2. However, if you'd like, you can still give @StephKoenig authorship!  When you commit, just add the flag `--author="Stephane Koenig <stephane.koenig@gmail.com>"` to your commit, and he will be given authorship on the patch.  It will look like [this commit](https://github.com/harvesthq/chosen/commit/d73404a19ce0d0517cbe4648edf5d08afeb43511) -- see how one user "authored" but another "committed"?  You'd be the "committed" there.

Thanks again for trying to be nice about it! :heart: :heart: :heart_eyes_cat: :heart:

**Comment by tremby** [comment]
I've had one too many patches get accepted but tweaked slightly by the maintainer and in the process my name stripped out of them to assume anything at all. But yes, in this case this seems like an excellent solution.

**Comment by StephKoenig** [comment]
@tremby feel free... you don't need my permission (kind of you to ask though). I'm not good with the whole patch stuff though, I always do the wrong thing with tabs and braces.

~Steph
