### ISSUE TITLE
Breaks draggable when inside draggable element.

### ISSUE THREAD

**Issue by radiosilence** [harvesthq/chosen#1911]
Basically speaking, if you do this:

    <div draggable="true>
        <select>...</select>
    </div>

Dragging works and you can see the contents of the div, but if you make that select a chosen, then you can't see the contents when dragging.

**Comment by pfiller** [comment]
That fiddle no longer lets me drag things in Chrome. I'm guessing they've changed the way draggable works. Makes sense since MDN calls it an [experimental technology](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable) whose spec is currently changing.

Going to #wontfix this. No sense spending time on something that's changing.
