### ISSUE TITLE
When standard placeholder text and selecting several times, last selection not possible to select

### ISSUE THREAD

**Issue by utkant** [harvesthq/chosen#2004]
Hi!

I am using chosen and have a selectbox with two options. When chosen is shown for the first time it shows the two options and the standard 'choose an option' text. If I then select first the first choice, then the second choise I get an error message saying: 

"TypeError: this.form_field.options[item.options_index] is undefined" in line 1002 in chosen.jquery.js.

The version in that file is 1.1.0.

Is this a known issue?

**Comment by pfiller** [comment]
I'm not able to recreate this issue, so I'm going to close it. It's quite old so it's possible it was fixed in an unrelated PR.

If you are still experiencing the issue, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce. Providing steps to make it happen helps also!
