### ISSUE TITLE
Width is too small on OSX Yosemite causing unnecessary line breaks in options

### ISSUE THREAD

**Issue by starzonmyarmz** [harvesthq/chosen#2128]
Since Yosemite has changed the styling of it's select boxes the width set on the Chosen element isn't wide enough. This causes options to either get an ellipses or broken to a new line.  
This is happening because the font size differs quite a bit from the native `<select>` element on Yosemite and the Chosen element, so when the Chosen element is set to the width of the native `<select>` element it isn't wide enough.

I was able to fix this by adding the following css to the native `<select>` element:

``` css
  border: 0
  font-size: inherit
```

Webkit select boxes are notoriously known to be almost impossible to style unless you modify the `border` property. So this simply breaks the default styling of the select box. Setting the `font-size` to `inherit` makes sure it's inheriting the font from the parent font-size. Arguably, I could have also set this to `100%`.

Here's the before and after:

![screen shot 2014-11-05 at 2 43 51 pm](https://cloud.githubusercontent.com/assets/171375/4924751/981f9ef2-6525-11e4-9bb4-95fd403f1f36.png)
## Is this an issue for Chosen or for the person using Chosen?

I kind of feel like this is something Chosen is responsible for. Chosen is suppose to behave very similarly as a browsers' default `<select>` would. Also, if an option is only one word it can get an ellipses which makes it hard to read the option. Example:

![image 2014-10-29 at 11 51 03 am](https://cloud.githubusercontent.com/assets/171375/4925086/4371ee3e-6528-11e4-895f-c40ca4c2e2d4.png)

Any thoughts about this @pfiller @adunkman @mlettini @tjschuck ?

**Comment by johnBgood** [comment]
Hi, any news about this bug ? I have the same on Ubuntu with Chrome. In Firefox it's a bit messy also.

**Comment by starzonmyarmz** [comment]
No news yet. @mlettini how do you feel about my proposed fix? Here's the same fiddle with those CSS properties defined: http://jsfiddle.net/c7jetd3z/3/

![screen shot 2015-03-05 at 10 42 37 am](https://cloud.githubusercontent.com/assets/171375/6508064/5d43ddb8-c324-11e4-9636-b19d317b859b.png)

**Comment by mlettini** [comment]
@starzonmyarmz 

I don't really like the fix you offered, because it's only indirectly fixing the problem. What is happening is in your fix:

The Chosen element normally gets a `width` set to it that is the current width of the select box it is replacing. By applying `font-size: inherit` (or 100%) to the select box now, it is growing in size because it is inheriting a larger-than-default font-size in this case. Then Chosen gets set to that bigger width, yet Chosen has a default of 13px and that won't change by changing the select box's `font-size`, so it has more room. Note that this fix does not work once the font-size it's inheriting is 11px small: http://cl.ly/image/1v0v191J0847 (not likely, but shows that it's an indirect fix).

So your change is circumventing the problem by making Chosen a wider width than it's supposed to be, because the select box it is replacing is now wider than it normally would be. This might work in Harvest's case, but probably not everywhere. It might also leave the user confused as to why Chosen is wider than the select box before it.

I do not have a better proposed solution as of yet. I think your fix is fine if it works for people that need a fix right now, and they can add it to their CSS. But I don't believe it should be a part of the Chosen repo.

**Comment by mlettini** [comment]
I actually believe the fix should be in JS. Rather than get the exact width of the current select box it is replacing, Chosen should know that it needs a different width. It is not the same font-size as the default select, and shouldn't try to behave as such by setting that explicit width. We should do a better job calculating the width Chosen needs to not have an ellipsis on the text, and therefore not have the option break lines in the dropdown.

**Comment by johnBgood** [comment]
I've created a jsfiddle showing the two main problems. One with short text, and the second where we always have the ellipsis.

I guess Chosen should just increase a bit the component width so that the text displays correctly.

http://jsfiddle.net/tjk2dffh/1/

**Comment by johnBgood** [comment]
Hi, isn't there any quick fix for my last jsfiddle ? this is very strange ...

**Comment by adunkman** [comment]
> Hi, isn't there any quick fix for my last jsfiddle ?

Feel free to find one, if you can, and share it here for the rest of us! :)

**Comment by johnBgood** [comment]
Of course ;) but I wanted to be sure it was a real bug because it's just a basic usage. I'll investigate on this
