### ISSUE TITLE
apostrophe not displaying correctly

### ISSUE THREAD

**Issue by hannolans** [harvesthq/chosen#2272]
All characters work fine, excluding the apostrophe:  *Agence de l'environnement et de la maîtrise de l'énergie* is displayed as *`Agence de l&#039;environnement et de la maîtrise de l&#039;énergie`*
![schermafbeelding 2015-03-18 om 12 20 43](https://cloud.githubusercontent.com/assets/899399/6707652/3cdce426-cd69-11e4-9072-fb16939b0eca.png)

**Comment by hannolans** [comment]
I'm using Drupal, and as a security measure all apostrophes in Drupal are changed to htmlentity. So we have to change this in Drupal I suppose. http://drupal.stackexchange.com/questions/56486/special-character-encoding-issues-in-node-titles

**Comment by tjschuck** [comment]
@hannolans As a workaround, how about changing it to be a true apostrophe (i.e. a "curly" apostrophe, i.e. `’` instead of `'`)?  Seeing as you have chars like `î` and `é` unescaped already, that should work.

However, rendering the options as plaintext (instead of HTML, including things like converting entities like `&#039;`) is intentional to avoid XSS vulnerabilities -- see https://github.com/harvesthq/chosen/pull/2254 and its linked issues for more information.

If you don't want your apostrophes auto-converted to escaped entities, that seems like something you'll have to take up with Drupal.  Perhaps its configurable/avoidable?

**Comment by hannolans** [comment]
Yes that is a good option. Thanks. Meanwhile I added an issue for the Drupal module as it's off course better when it do work in Drupal: https://www.drupal.org/node/2454609
