### ISSUE TITLE
Do not use <ul>

### ISSUE THREAD

**Issue by mJeevas** [harvesthq/chosen#2278]
Do not use unordered list as plugin layout. Rewrite it with divs.
In some cases ``<ul>`` has their default styles like :before list style markers or font-size or something.

So it causes styles mess. Use lists as it intended (as simple list in text) and not as layout.

**Comment by stof** [comment]
Well, we use the semantic tag to represent a list of results. This seems sensible to me.

**Comment by kevin-brown** [comment]
Just wanted to chip in to mention that lists are semantically correct for a _list of results_. And it's one of the preferred ways to have an accessible combobox.

http://test.cita.illinois.edu/aria/combobox/combobox3.php

**Comment by tjschuck** [comment]
Agree with both @stof and @kevin-brown -- using `ul`s in this way is completely valid.

> Use lists as it intended (as simple list in text) and not as layout.

That hasn't been the conventional wisdom for more than a decade.  Here's [an ALA article from _2002_](http://alistapart.com/article/taminglists/) about using lists semantically instead of just as visual bulleted lists.
