### ISSUE TITLE
Unable to use triangle brackets in data-placeholder text

### ISSUE THREAD

**Issue by fedulovivan** [harvesthq/chosen#2314]
initializing chosen with following markup
```
<select data-placeholder="&lt;None&gt;">
<option></option>
<option value=1>Value 1</option>
</select>
```
leads to empty widget instead of displaying text '&lt;None&gt;' it it
![empty widget](https://cloud.githubusercontent.com/assets/752105/7252462/f4579cec-e83d-11e4-961c-d9161f19a204.png)

this reproduces after upgrading to version 1.4.2 from 1.3.0

**Comment by fedulovivan** [comment]
Any comments?

**Comment by avinash2** [comment]
I'm having a similar issue when the options contain angular brackets or even the HTML entities for them. For example:

<option>Mr. Smith &lt; mrsmith@gmail.com&gt;</option>

will only get submitted as: Mr. Smith 

The whole text wrapped with "<" & ">" or "&lt;" and "&gt;" gets swallowed somehow. Also, when the options contain "<" & ">" instead of entities, the values wrapped between "<" and ">" aren't even displayed on the front end.

Please help! (Using Chosen ver. 1.4.2)

Thanks!
