### ISSUE TITLE
Disabling / Re-enabling Multi-select causes strange behavior

### ISSUE THREAD

**Issue by qnotemedia** [harvesthq/chosen#2335]
I have a multi-select that I'm setting to disabled while waiting for an ajax call via 

$('select').attr('disabled',true);
$('select').trigger('chosen:updated');

After the ajax call is complete, the select is then re-enabled:

$('select').removeAttr('disabled');
$('select').trigger('chosen:updated');

The visual representation definitely mostly works. I can click to show the options, and click and option fine. I can also type out an option title and choose it with the enter key.

What doesn't work is typing an option title and clicking on it with the mouse. Enter key works, but clicking doesn't. The item does not get added to the list.

When I remove the disable/re-enable functionality, everything works as it should.

**Comment by pfiller** [comment]
Just put together a Fiddle to try and reproduce this and it works as expected for me (searching and then choosing a result with a mouse is ok): https://jsfiddle.net/jy3sz5pk/

This bug is about a year old so it's entirely possible this bug was fixed by a new version of Chosen. If you're still seeing it and can put together a Fiddle and tell us what browsers/OS to look into, we'll re-open this.
