### ISSUE TITLE
Add option for minimum term length to start search

### ISSUE THREAD

**Issue by panmari** [harvesthq/chosen#2359]
I have a select field that has very many options (with large descriptions). When only entering one character, the search lags noticeably, leading to a bad user experience. 

This could be improved by only starting the search after entering n characters of the search string. Is there already such an option in chosen? If not, would it be worth implementing?

**Comment by tjschuck** [comment]
Related:

* https://github.com/harvesthq/chosen/pull/1225
* https://github.com/harvesthq/chosen/pull/1109

Another option instead of waiting for _n_ characters would be to add some kind of debounce functionality to not trigger the filtering until the user has stopped typing instead of on immediately upon every keypress.

**Comment by panmari** [comment]
My pull request doesn't show any results at all until the minimum number of characters are entered for search. It would possibly be preferable to either

a) Show a hint that there are more characters required
b) Show all results (unfiltered)

Unfortunately I'm not familiar enough with the codebase to implement these features. But the tests I provided can be easily adapted to test such behavior.

**Comment by tjschuck** [comment]
Closed by #2362

**Comment by panmari** [comment]
Solved with alternative approach, as described in #2362
