### ISSUE TITLE
Visual Representation of disabled but nonetheless selected elements wrong

### ISSUE THREAD

**Issue by transentia** [harvesthq/chosen#2374]
The way chosen displays a disabled option is wrong.

I have a chosen select with an option list that includes some disabled options. I update the select (in response to an AJAX call returning) using code like:

    select.val(data).trigger("chosen:updated").change();

If the option corresponding to the value of `data` has the disabled attribute, chosen displays it as a normal entry, without any CSS styling to indicate that it may not actually be selected.

To be clear, I am talking about the styling of the un-expanded select, not the options list UI that displays in response to a mouse click.

A workaround is:

    select.on('change', function(event, params) {
        $('#select_chosen > a:nth-child(1) > span:nth-child(1)').css('color', ($('#select :selected').attr('disabled') == 'disabled') ? '#CCC' : '#444');
    });

I use jquery 1.11.3/chosen 1.3.0. tested on firefox/ie.

**Comment by transentia** [comment]
And a generic version of the above fix is:

            $('.chosen-select').on('change', function(event, params) {
                $(this).next('.chosen-container').find('a:nth-child(1) > span:nth-child(1)').css('color', ($(':selected', this).attr('disabled') == 'disabled') ? '#CCC' : '#444');
            });

**Comment by tjschuck** [comment]
@transentia Please update to the [latest version](https://github.com/harvesthq/chosen/releases) of Chosen. The latest release version (used on the [Chosen demo page](http://harvesthq.github.io/chosen/)) does not show this issue.

A selected-but-disabled option gets styled as such:

![](http://monosnap.com/image/pcpnH7kGlmEu4gfwYWR2NGosKYzkQ9.png)

Here are the styles for that class: https://github.com/harvesthq/chosen/blob/0101370d1a063ecefd7d8553fc0ad53850065b07/sass/chosen.scss#L274-L280

Thanks for reporting your workaround for anyone who can't update to the latest.

**Comment by transentia** [comment]
Thanks for the quick reply. Much appreciated. Thanks also for pointing out the styles for me.

Sorry, but I think you closed this too soon.

I have updated to the latest version and removed my workaround. 

The issue persists; see the associated image.
![chosen](https://cloud.githubusercontent.com/assets/105110/8798930/5f7d47ae-2fe9-11e5-9416-640e016e0779.png)

You can see that the browser has retrieved chosen v1.4.2 JS (also the css, of course, but not shown) but look at the selected option 'Bare.' it is clearly disabled in the expanded option list (shows Gray) but the displayed value of the select 'Bare' (of course) is NOT styled in the same way.

This is on OSX with Firefox developer version. I see the same on Safari and Chrome. My workaround still works.

Cheers.

**Comment by tjschuck** [comment]
Aha, you're talking about a single select, not a multiple select.

Chosen seems to behave just like the native select does (which is the typical inspiration for ambiguities like this), so I think this is okay as-is.

Native multiple select, two elements selected, and one of those (Afghanistan) disabled:

![](http://monosnap.com/image/BkdS6wwvt6byE5WJsEJTzU1IkyP35V.png)

Native single select, one element selected-and-disabled, closed -- note there's no stylistic difference between disabled or not when selected:

![](http://monosnap.com/image/kVGADjPGCzq8RoOPrn4PWSYrsNGJ38.png)

And open:

![](http://monosnap.com/image/tJbwNjK9SqcdjGA31lcouhrtwjdvEk.png)

Here's the Fiddle with those native examples: http://jsfiddle.net/4c8m2wkv/

I think graying out the option would be a more problematic UI for single selects, since that would imply that the select _itself_ is disabled, which is not the case.

**Comment by transentia** [comment]
You know, I didn't think to check the actual select widget's behaviour!

I'm feeling stupid.

And you make a very good point about the select itself appearing to be disabled...

Thanks again for your help.

**Comment by tjschuck** [comment]
@transentia No need to feel stupid!  I hadn't ever actually thought about this problem before, and I don't know that anyone else had either :)

Thanks again for your initial report and for providing the workaround -- that will certainly help future people that find this thread.
