### ISSUE TITLE
Ipad

### ISSUE THREAD

**Issue by taras-pixelant** [harvesthq/chosen#2386]
Hello guys )
I found issue, 'chosen' doesn't work properly at iPad, how can I fix it ?

**Comment by easy-one** [comment]
Good shoot, but not much informative. Yes, it performs bad on iPad. But how?

My bugs:
- dropdown does not close when clicked outside of it
- in multiple select mode, I cannot deselect items. The "cross" is not clickable
- iPad has a feature of scrolling the document, in order to center the focused element. This feature is sometimes unwanted, for example when the dropdown is placed inside a popup. 

To be continued

**Comment by donthebike** [comment]
Just to be sure you know: the Ipad problems were mentioned by a lot of people already in https://github.com/harvesthq/chosen/issues/2289

**Comment by tjschuck** [comment]
Thanks @donthebike -- closing this in favor of that issue, which has a lot more information.

@taras-pixelant @easy-one Please leave any additional feedback you have on #2289
