### ISSUE TITLE
trigger update not update properly

### ISSUE THREAD

**Issue by craigcosmo** [harvesthq/chosen#2388]
I have these dependent selects. what it does is, when you select a city in one select. The other select will list out the districts of that city. 

what's wrong is, when the html re-populate selects, chosen seems not updating it properly.

You can try the example I attached. Disable chosen and see how it work, then enable chosen with trigger update, you will see the problem.

https://www.dropbox.com/s/stcrqcohbjjv7ju/multiselect%204.zip?dl=0

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

The `.trigger('chosen:updated')` functionality works, so the issue is probably with something in your specific implementation.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

I also recommend you share your demo via a [Fiddle](http://jsfiddle.net) so that people don't have to download and open a .zip file from an untrusted source, and they can just see your issue and share corrections directly in the browser.

**Comment by craigcosmo** [comment]
you are right, there was a flaw in my implementation.
