### ISSUE TITLE
Privious value selection

### ISSUE THREAD

**Issue by priyesh221292** [harvesthq/chosen#2401]
Hello sir,
i am new user of chosen and in my web application i dynamically add select box on add button click event.when new select box appears it has the same value as previously selected opion and can not be updated.
![1](https://cloud.githubusercontent.com/assets/13570506/9197800/1771f636-4055-11e5-9b7e-1005e5e6b9df.PNG)
![2](https://cloud.githubusercontent.com/assets/13570506/9197802/1b2f0818-4055-11e5-9a6a-4e2f486bdf6d.PNG)

**Comment by stof** [comment]
Are you using the same id for all select boxes ? this could cause the issue. Ids are required to be unique in HTML, and the ``document.getElementById()`` function in Javascript relies on that behavior (browsers are optimizing the access by id).
If you have duplicate ids, this could cause this issue in Chosen.

the other possible cause could be that you are duplicated the DOM of the row including the elements created by chosen instead of duplicating the select and then applying chosen on it. In this case, you would have the UI for chosen in your new row, but without the JS listeners to make it work.

**Comment by tjschuck** [comment]
Without a way for us to reproduce you're specific situation, @stof's answer is probably the best we can offer.

However, the GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.  For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

Additionally, if you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue directly, you'll be much more likely to get actionable help.

**Comment by priyesh221292** [comment]
Yes i am using the same id's and i know this is causing problem but is
their any possible solution?
