### ISSUE TITLE
TypeError: this.form_field.options is undefined

### ISSUE THREAD

**Issue by comtronix** [harvesthq/chosen#2404]
When submitting my form (with 2 chosen multiple fields) i get this error:

TypeError: this.form_field.options is undefined
..is.disable_search || this.form_field.options.length <= this.disable_search_thres...
chosen.jquery.js (line 829)

**Comment by comtronix** [comment]
is there a way to fix this error?

**Comment by QuestionDevelopment** [comment]
This error is due to initializing chosen upon an element that has no option tags.  For example, if you run

```
$('#example').chosen({no_results_text: 'No grape found', allow_single_deselect: true});
```

And example is an the id of a button (not a select) then you will see this error.  If the item is a select then perhaps you are using the id twice on the page...the script will choose the first usage.

You can stop this error by updating line 829 as

```
                if (this.disable_search || typeof this.form_field.options === 'undefined' || this.form_field.options.length <= this.disable_search_threshold) {
```

and 148 as

```
this.allow_single_deselect = (this.options.allow_single_deselect != null) && (typeof this.form_field.options !== 'undefined') && (this.form_field.options[0] != null) && this.form_field.options[0].text === "" ? this.options.allow_single_deselect : false;
```

but that is simply handing the invalid data properly and will not make the script work.  I'm not sure if these changes are recommend as the error at least gives the user a clue as to what is going wrong...opposed to everything running properly (no errors) but not initializing.

**Comment by koenpunt** [comment]
If you add an empty option to the select you're applying Chosen to, it should resolve your problem. Although I agree that it would be better if an empty select doesn't cause errors.

**Comment by pfiller** [comment]
I'm not able to recreate this error. What browser is/was it happening in?

Here's a Fiddle showing it working on two selects with no errors in the console: https://jsfiddle.net/mr4p6sje/

**Comment by mariofertc** [comment]
Hello I'll fix this error adding a condition at the line 151
if(this.form_field.options.length>0) {        
and at the line 153
}else{this.allow_single_deselect = false }

**Comment by brynnb** [comment]
Just leaving this here in case it helps anyone else: I changed my selector to target the dropdown by ID instead of Class and it fixed this. I suspect there was something about my CMS that I'm using that duplicated the dropdown without options or some other funkiness.
