### ISSUE TITLE
Suggestion: New update event without cleaning inputbox  

### ISSUE THREAD

**Issue by despinola** [harvesthq/chosen#2421]
I have an autocomplete pulldown that is filling "options" from server using AJAX. Once I have added all options into select, I launch a chosen:updated.chosen event which refresh the pulldown correctly but my problem is that it also cleans the input text and this is quite strange.

Two possible solutions:
1- Create a config property that allows to clean or not the text box on updates event and add an if on results_build function.
if(newProperty) this.show_search_field_default()
2- Instead of creating a property, create a new event to do the same

Thanks

**Comment by kindziora** [comment]
I see the same issue, a descent solution would be nice. By now i just set the search field value back to the original value before the "chosen:update" was triggered.

**Comment by pfiller** [comment]
The "chosen:updated" function wasn't really intended to make it so that Chosen could drop in as an autocomplete library. I don't think I'd get behind a PR that added an option like this as it falls outside of the expected use of Chosen.

@kindziora's solution seems promising enough for people who want to try and wrestle Chosen into AJAX autocompleting shape.
