### ISSUE TITLE
Inline styles and Content Security Policy

### ISSUE THREAD

**Issue by penartur** [harvesthq/chosen#2423]
As of now, Chosen for JQuery does not work correctly when inline styles usage is forbidden by an appropriate Content-Security-Policy.
The problem is that, when it creates the "chosen" menu in set_up_html, it uses "style" param to specify width: https://github.com/harvesthq/chosen/blob/910a12599c10a11b7005feedb1e53e4b4535100e/coffee/chosen.jquery.coffee#L35
JQuery supports specifying the width directly (not by CSS properties): http://api.jquery.com/width/ ; this one should solve the problem.

Unfortunately, writing front-end JS compatible across different browsers (and testing it) is not my strong side, so I'll only create this issue, and will not supply any pull request with it.

**Comment by stof** [comment]
@penartur jQuery.width sets inline styles too.

**Comment by okdana** [comment]
Bumping. This is still an issue — Chosen does not like CSP very much.

Here's an example of the kind of errors you get with `style-src: 'self'` (using Chrome here because its console output is more explicit, but the same problem occurs in Firefox or where-ever):

![screen shot 2016-10-07 at 19 46 02](https://cloud.githubusercontent.com/assets/122095/19208987/ceaa9438-8cc7-11e6-9cc3-c69f730de884.png)

[This](https://github.com/harvesthq/chosen/blob/7259f35c8cb81b53cc470f002dd6d374f7257ee3/coffee/chosen.jquery.coffee#L500) is what causes that particular error:

```js
div = $('<div />', {
    'style': style_block
});
```

However, there are issues in other places, too, like [here](https://github.com/harvesthq/chosen/blob/7259f35c8cb81b53cc470f002dd6d374f7257ee3/coffee/chosen.jquery.coffee#L36) (the line OP linked) and [here](https://github.com/harvesthq/chosen/blob/7259f35c8cb81b53cc470f002dd6d374f7257ee3/coffee/chosen.jquery.coffee#L44).

I am not a super expert front-end dev either, but as far as i understand it, this is caused by writing directly to an element's `style` attribute. Modifying individual properties on an [`HTMLElement`'s `style` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style), on the other hand, should not run afoul of these restrictions.
