### ISSUE TITLE
Bug with tabindex when you click Tab keyboard key single select

### ISSUE THREAD

**Issue by bruts** [harvesthq/chosen#244]
http://harvesthq.github.com/chosen/

this bug also you can see on your page first select box.

**Comment by akurtz** [comment]
This bug still occurs with the latest version of Chosen (v1.4.1) -- only in Firefox.  It did not occur in Chrome, Safari, or IE.

Versions tested:
- Firefox 36.0.4 Mac -- bugged
- Firefox 36.0.4 Win -- bugged
- Chrome 41.0.2272 Mac -- OK
- Chrome 41.0.2272 Win -- OK
- Safari 8.0.3 -- OK
- IE 11.0.9600 -- OK
- IE 10.0.9200 -- OK

It's still fixed in Firefox with `$('div.chzn-container ul').attr('tabindex',-1);` with no negative effect on the other browsers.

Are we calling this a Firefox bug that won't get a fix in this package?
