### ISSUE TITLE
Does not work on Android tablets (e.g. Nexus 9)

### ISSUE THREAD

**Issue by mydea** [harvesthq/chosen#2443]
I know that there is quite a bit going on around the topic of mobile support. However, I'm not sure if this issue is known or if this is a "new" bug. On my Android phone (Nexus 4), chosen works as expected (= it falls back to a native select, which works fine). However, on my android tablet (Nexus 9), chosen is displayed normally, which would be OK, but it is impossibly to select an option in the list. This means that I can filter normally, and everything works fine, but I cannot select an entry by clicking on it.

**Comment by tjschuck** [comment]
@mydea Here's the rule for disabling Chosen on Android: https://github.com/harvesthq/chosen/blob/adf64cca88a69f0cb5a37d10c90bc32de774e059/coffee/lib/abstract-chosen.coffee#L287-L288

As you can see there, any user agent that has `Android` _but also_ `Mobile` is blocked.

I assume your Nexus 9 is considered "non mobile" by user agent.  Can you send the user agent that your tablet provides?

Anyway, assuming your Nexus 9 is `Android` but not `Mobile`, this seems to be behaving as intended.  However whether that check is _sufficient_ is worth discussing.

I'm going to edit the title of your issue to make it slightly more accurate for what the issue is.

**Comment by mydea** [comment]
Yeah, I agree that it is correct to display chosen on the Nexus 9. However, it should be possible to select options there, shouldn't it?

**Comment by tjschuck** [comment]
> However, it should be possible to select options there, shouldn't it?

Based on the rules, I would hope so!  But I can't confirm or deny (no Android tablet), so your report stands.  If you can figure out a fix, PRs encouraged!

Just to round out your report, can you clarify what browser, browser version, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?  Can you confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) (which is running the latest version) shows the issue?

**Comment by mydea** [comment]
Sure:

Nexus 9
Android 5.1.1
Chrome for Android 45
User Agent: Mozilla/5.0 (Linux; Android 5.1.1; Nexus 9 Build/LMY48M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Safari/537.36

I also tried the Chosen demo page, it's the same there: the chosen select apepars, but I cannot select an option.

I guess it would be an option to just drop the additional "is mobile" check for android browsers?

**Comment by chrisdeeming** [comment]
Hello,

We have a user who is experiencing an identical issue:

>I've checked on the Chosen demo page and the issue still remains, I can't select anything from the Chosen lists on the right hand side.
>
>My user agent is:
>
>Mozilla/5.0 (Linux; Android 5.1.1; SGP612 Build/23.4.A.1.200) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36

Incidentally they have identified a workaround which involves typing into the search/filter box and hitting return/enter. Doing so selects the desired item.

**Comment by rs-orlov** [comment]
Hi,

there are another similar bug discovered on iPad.
1. It's imposible to scroll options list because of `"touchstart.chosen"` event handler binded to `@container` evaluates `evt.preventDefault()`
2. It's imposible to remove an option from multiselect

**Comment by mydea** [comment]
Is there a plan to fix this anytime soon? This is a pretty major bug imho.

**Comment by mydea** [comment]
Is there an update on this? I rechecked, it works on Android & iPhone (chosen is not loaded) and iPad (chosen loaded and works), but not on an Android Tablet (Nexus 9). This is a serious bug and it would be great if someone could take a look at this. It is a pretty easy fix.

**Comment by berniechiu** [comment]
Having this issue, too.
Wish there might be a hotfix or workaround.

**Comment by nikulinsanya** [comment]
The same issue! Are there any workarounds?

**Comment by Nicolai8** [comment]
I have the same issue.

The problem is in how events are fired on Android Chrome, i.e. even if you just tap the item the following events are fired:
touchstart -> touchmove -> touchend 
due to this _touchmove_ event chosen doesn't select any value:

    AbstractChosen.prototype.search_results_touchstart = function(evt) {
      this.touch_started = true;
      return this.search_results_mouseover(evt);
    };

    AbstractChosen.prototype.search_results_touchmove = function(evt) {
      this.touch_started = false;
      return this.search_results_mouseout(evt);
    };

    AbstractChosen.prototype.search_results_touchend = function(evt) {
      if (this.touch_started) {
        return this.search_results_mouseup(evt);
      }
    };

So I made workaround, it based on assumption that when we scroll value offset of _target(li)_ is different on _touchstart_ and _touchend_:

    AbstractChosen.prototype.search_results_touchstart = function(evt) {
      this.touch_started = true;
      this.touch_started_offset = $(evt.target).offset().top;
      return this.search_results_mouseover(evt);
    };

    AbstractChosen.prototype.search_results_touchend = function(evt) {
      if (this.touch_started || this.touch_started_offset === $(evt.target).offset().top) {
        return this.search_results_mouseup(evt);
      }
    };

P.S. Known issue with this workaround: I know is buggy at least when you scroll down(up) and then up(down) to the same position in one scroll.

**Comment by nervgh** [comment]
Same here.
It looks like the bug has fixed.
When will release the version of chosen with these fixes?
Thanks.
