### ISSUE TITLE
bower: chosen.min.css not same as chosen.css cases autoprefixer to stop work

### ISSUE THREAD

**Issue by AndorLundgren** [harvesthq/chosen#2444]
When using bower to install chosen:
bower install --save-dev chosen
installed files are:
.bower.json
bower.json
chosen.jquery.min.js
chosen.min.css
chosen-sprite.png
chosen-sprite@2x.png

The installed file chosen.min.css is not the same shown in the git repo chosen.css.
In the chosen.min.css file the css
linear-gradient(top... is used which causes
autoprefixer to not create a .map file (ie stop autoprefixer to work).
This makes the grunt repo unusable for me and probably many more.

Please fix it.

**Comment by tjschuck** [comment]
@AndorLundgren That was fixed in https://github.com/harvesthq/chosen/pull/2364/, which has not yet been rolled into [a release version](https://github.com/harvesthq/chosen/releases) of Chosen.

If you need the updates from master sooner, you can download and build the source yourself in the meantime.

**Comment by AndorLundgren** [comment]
Thank you for the fast answer. Sorry I did not search enough to find out you already fixed it.
