### ISSUE TITLE
v1.2.0 available on bower

### ISSUE THREAD

**Issue by sebastianzillessen** [harvesthq/chosen#2473]
Hi there,

we use v1.2.0 in one of our projects and would like to include it via bower. Can you please make this package available in the bower-chosen repository? Only Version 1.4.1 and 1.4.2 are available there.

Thanks.

PS: by the way, please consider migrating to default bower structure, where the src and the release files are in the same project repository! Thanks!

**Comment by stof** [comment]
having both in the same repository was done in the past, and it was a maintenance nightmare: it means that as soon as you merge a PR, all other PRs are not conflicting because of the minified files. This is why we stopped doing it (and why we rejected supporting bower for years).

I suggest you to update to the latest version of chosen rather than asking to build old versions for bower. Bugs have been fixed between 1.2.0 and 1.4.2

**Comment by pfiller** [comment]
I agree with @stof. We're definitely not going to add builds of old versions. And maintaining the generated files in this repo was a disaster.
