### ISSUE TITLE
Gradient syntax is outdated

### ISSUE THREAD

**Issue by anselmbradford** [harvesthq/chosen#2491]
The generated CSS is giving this autoprefixer error: `Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.` According to [this](https://github.com/postcss/autoprefixer/issues/530) it should be `to bottom` instead of `top`, but it appears this is the issue with how the CSS gets generated so may not originate in this repo.

**Comment by tjschuck** [comment]
Already fixed by https://github.com/harvesthq/chosen/pull/2364, just not yet rolled into a released version.

You can either pull down Chosen master and build it yourself, or stay tuned for a new release soon that will include the fix.  It will be [posted to the Releases page](https://github.com/harvesthq/chosen/releases) when it's done.
