### ISSUE TITLE
disable_search_threshold removes keyboard support

### ISSUE THREAD

**Issue by aaronspence** [harvesthq/chosen#2593]
If you use disable_search_threshold you can no longer type for example U and the dropdown scroll down to the U options. Default select has this functionality is it possible for chosen to follow suit.

Thanks,
Aaron

**Comment by wallybhoy** [comment]
Yeah, this is really annoying. One thing preventing me from using this as it takes away from the accessibility that is on a standard select input by default.

**Comment by pfiller** [comment]
I don't really see a way around this. Using `disable_search` explicitly disables the search field and makes it invisible by design. That's the only way we have to capture keyboard input so it's pretty much a non-starter to try and fix this problem.

I'd suggest not using `disable_search` or not using Chosen.
