### ISSUE TITLE
Make dropdown opening and closing bound to the same event

### ISSUE THREAD

**Issue by evil-shrike** [harvesthq/chosen#2614]
Currently dropdown opens on mousedown but closes on mouseup outside the list.
When we click inside control it doesn't make sense. But if input's size/position change on dropdown opening then mouseup can happen outside the input and so it closes the dropdown immediately. 

It can be easily reproduces if click and hold mouse button then move outside dropdown and release the button - dropdown closes.

But there could be real cases. For example: we changed styles of choose in such a way that its dropdown drops not as popup but inside dom instead. This makes other elements move below. And that can cause scrollbar appearance. And scrollbar appearance causes chosen to change width. So cursor appears outside input. 
Here's a demo I captured:
![choosen_jumps](https://cloud.githubusercontent.com/assets/1203230/15754922/206e3096-2903-11e6-9e87-51a8ea16ebd7.gif)

Version: 1.5.1

**Comment by pfiller** [comment]
Sorry, but I think this is expected behavior. If someone clicks outside of Chosen, it should close. Your modification of Chosen to display inline should include a modification that accounts for this listener.

**Comment by evil-shrike** [comment]
It's not a click outside, it's a releasing button outside which is not the same. Click was inside.
Our modifications is only CSS overrides. While replacing mousedown/mouseup handlers would require forking.

**Comment by pfiller** [comment]
Sorry - I wasn't very clear. I understand that your situation is not a click outside. But the browser is triggering a click event at the point of mouseup and the event will be triggered on something that is not Chosen. Clicks on something that's not Chosen are specifically handled in a way that closes any open instances of Chosen.

> Our modifications is only CSS overrides. While replacing mousedown/mouseup handlers would require forking.

I appreciate that, but Chosen can't possibly be expected to account for every modification of its code -- CSS or otherwise. We can only make it work for the most common use cases!
