### ISSUE TITLE
Incompatibility with jquery DataTable

### ISSUE THREAD

**Issue by slbtuga** [harvesthq/chosen#2619]
Hi.

I creating a new header row for filter data in [datatable](https://datatables.net/).
For some columns, I want use a list of values that I can pick one and filter row data for that value.
For this, I wold like to use the [chosen plugin](https://harvesthq.github.io/chosen/).

Whats happen clicking in chosen control to pick one value is, when I define the datatable options `scrollX` or `scrollY`, the header change to a bad look and the dropdown of plugin stay beyond row data of datatable.
But, if I remove this options, everything works fine - as expected.

[Here an example](https://jsfiddle.net/sja9v7Lu/6/)

Can some one help me resolve this?
I realy appreciate if some one help me with this.

Thanks.

**Comment by pfiller** [comment]
I see a few things happening here:

1. When I click on Chosen, the header area is scrolling and my cursor then selects the first item in the dropdown. That's what cuases your column widths to changing. I'd probably turn off that scrolling.
2. Chosen is staying behind the data because the header has overflow hidden turned on. See #92 for a discussion of that.

Good luck!

**Comment by slbtuga** [comment]
Thank you for your answer.
I did not get what o mean.
I'm very new in web world, especially in jquery/javascript.

Can you write a solution that work in this case, please?
Thanks.

**Comment by pfiller** [comment]
Sorry, @slbtuga. This is a project we do in our spare time and we can't spend time debugging specific cases. I'd suggest trying StackOverflow for help with a specific solution -- there's even a `jquery-chosen` which may be helpful.

**Comment by slbtuga** [comment]
ok.
Thank you anyway.
