### ISSUE TITLE
RTL search and select issue 

### ISSUE THREAD

**Issue by wilz05** [harvesthq/chosen#2620]
Hello thank you for the awesome product.. it really works great with english search 

But Arabic search results doesn't filter properly. it filters based on contains criteria 

for example you look for "ال"  instead of showing list item number 1,3,2 results from the below. it works like a contains search 
ال يبلشى( 1
2) لسل الىاد
3) الثقصعلا 

In chosen settings search_contains:false, still it filters based on contains criteria.

Could you please review this issue.

**Comment by pfiller** [comment]
So, this is a bit tricky for me to understand since I can't read even a tiny bit of Arabic ... but I think I understand what's happening. When you do an Arabic search, the browser seems to be automatically understanding it's Arabic and flips the direction of search.

"ال" should match all 3 results because it's the start of a word in all three matches. The equivalent in english would be something like this:

1. To Infinity!
2. Rotten Tomatoes 
3. Tornado

A search for "To" would match all three of these results since "To" is the start of a word. To see that `search_contains` is working correctly in your example, try and search for "ىا". That search will only match if you have `search_contains: true`.

**Comment by wilz05** [comment]
I have tried with the value, true and false for "search_contains". both are working in the same way like contains works. this issues is only for arabic. for english all good. 

like you explained earlier
"ال" should match all 3 results because it's the start of a word in all three matches. The equivalent in english would be something like this:

**To** Infinity!
Rotten **To**matoes
**To**rnado


If there is a way to get it done like the below 
**To** Infinity!
**To**rnado
Rotten **To**matoes

will be much appreciated
