### ISSUE TITLE
Country list snaps to bottom when mouse into list box

### ISSUE THREAD

**Issue by joebeaver89** [harvesthq/chosen#2621]
Example can be found at https://www.broadbandgenie.co.uk/mobilebroadband/tools/mobile-broadband-abroad

I have noticed that when I open the country list box and move my mouse into it the list snaps to the bottom of the list. I can scroll around but as soon as I move my mouse in the box it snaps back down to the bottom of the list.

### Steps to reproduce

  1. Go to https://www.broadbandgenie.co.uk/mobilebroadband/tools/mobile-broadband-abroad

  2. Open country list and move mouse into box. 

  3. Scroll and move mouse around in the box

### Expected behavior

Should not snap to bottom of list

### Actual behavior

Snaps to bottom of list

### Environment

  - **Chosen Version**: 1.5.1 (not on the link given but have tested on 1.5.1 and same behaviour)

  - **jQuery or Prototype Version**: 1.12.0

  - **Browser and Version**: Chrome/Edge/FireFox (latest)

  - **OS and Version**: Mac OS X 10.11.3 & Windows 10

**Comment by pfiller** [comment]
I'm not seeing that happening anywhere else so it seems pretty clearly to be a conflict with something on that page. I'd start by looking for any conflicting mouse listeners or plugins that may be attaching events to the same element. You may want to try slowly removing plugin files until it starts working as expected again ... that'll help you identify the source potentially.

Otherwise, I'd try something like StackOverflow for help. Our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests so it's not the best place for debugging specific pages. You can explore the jquery-chosen tag on StackOverflow or just post a question. You'll be more likely to get a quick answer there.

**Comment by joebeaver89** [comment]
Looks like it might have been a bug in jQuery 1.12.0, updated to 1.12.4 and it no longer happens
