### ISSUE TITLE
Chosen site still lists 1.5.1 version as latest

### ISSUE THREAD

**Issue by vandrijevik** [harvesthq/chosen#2649]
The [Chosen site](https://harvesthq.github.io/chosen/) still wrongly lists 1.5.1 as the latest available version (instead of 1.6.1).

![screen shot 2016-07-20 at 14 43 16](https://cloud.githubusercontent.com/assets/7736/16986702/4ebfdb48-4e88-11e6-9d26-734672827c83.png)

This is because [the `gh-pages` branch](https://github.com/harvesthq/chosen/tree/gh-pages) of this repository, which is used to serve the static site, has not been updated since 1.5.1. Instead, the commits 2610f21fb02f3bdc1001106dae0e65f480829c9b and b36a0d6631064919f9771d785066171d861d1d46 (to update to 1.6.0 and 1.6.1 respectively) have been made on `master`, and update files in the `public/` directory.

Since the contents of [`public/` on master](https://github.com/harvesthq/chosen/tree/master/public) are different from the contents of the [root of the `gh-pages` branch](https://github.com/harvesthq/chosen/tree/gh-pages), I am not sure how the `public/` directory is meant to be used or if it is necessary, so I am opening this issue before proceeding with a PR.

I propose that the `public/` directory be deleted from the `master` branch (so that branch is used for developing the library only), and that all documentation reside only in the root `gh-pages` branch, following [standard GitHub Pages practices](https://help.github.com/articles/creating-project-pages-manually/#create-a-gh-pages-branch).

If this is okay with everyone, I’ll do that cleanup in a follow-up PR which will update the site appropriately.

**Comment by tjschuck** [comment]
Re: removing the `public/` dir, I don't really have much of a preference there, honestly.

However, obviously the gh-pages branch should get updated with new releases. But it should be automatic!  We have [tasks to build and tag and release new versions](https://github.com/harvesthq/chosen/blob/db00adc2c01eda07a9d04dd1832ec8c62c709bba/Gruntfile.coffee), and _historically_ that also had some magic to push the new `public/` contents to gh-pages.  If you could restore that, I'd give you many upward-pointing thumbs.  Like, 15?  20?

/cc @pfiller and @koenpunt, since they recently did an overhaul of the release process in #2550.

**Comment by koenpunt** [comment]
There still is a `gh-pages` task: https://github.com/harvesthq/chosen/blob/db00adc2c01eda07a9d04dd1832ec8c62c709bba/tasks/package.coffee#L19-L23

We have to test if that will work in the packaging from Travis.

**Comment by koenpunt** [comment]
At least for now I've manually updated the GitHub page. I will open an new issue for the auto-publishing of it
