### ISSUE TITLE
Need comma separated value

### ISSUE THREAD

**Issue by ibnbd** [harvesthq/chosen#2664]
Working with Chosen Select option with multiple. Upon submitting the form values of select post as same name.

```
my_select = Value 1
my_select = Value 2
my_select = Value 3
```

So I am just able to catch single value, is there any way transfer the values as comma separated values. Example

`my_select = Value 1,Value 2,Value 3`

Please let me know if anyone knows this solution.

Thanks

**Comment by tjschuck** [comment]
@ibnbd This is actually just how regular multiple `select` fields work — Chosen is just visually styling on top of one, but the submitted form is still just the underlying `select`.

What you probably need to do is just add `[]` to the name of your select, and then the POST value will contain an array of selected values.

Instead of:

```html
<select name="my_select">
...
</select>
```

You should use:

```html
<select name="my_select[]">
...
</select>
```

**Comment by ibnbd** [comment]
Thank you for your reply @tjschuck

```
Array
(
    [my_select] => Array
        (
            [0] => 255
            [1] => 256
            [2] => 257
            [3] => 259
        )

)
```

After doing so my data coming as array, but is there any solution on this plugin to turn values in comma separated?


Thanks

**Comment by tjschuck** [comment]
Hi @ibnbd — nope, no support for that out of the box, because Chosen aims to just be a skin on top of a traditional `select`, changing the functionality as little as possible.

You can probably do what you're after with some after-market JavaScript, but that's outside of the scope of Chosen.  However, it's probably easier to do what you want serverside — turning an array into a comma-separated string is usually pretty trivial, although it depends on your environment.  Maybe try asking on [StackOverflow](http://stackoverflow.com) with some more specifics!  You're much more likely to get a quick answer there.
