### ISSUE TITLE
TypeError: this.form_field.options[item.options_index] is undefined

### ISSUE THREAD

**Issue by usmanshah** [harvesthq/chosen#2682]
Summarize your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. dont provide a default option thats already selected
  2. Select all options one by one, it messes up the array indexing and on selecting an option, the next one is selected instead of it. i.e if i try to select option 2 , option 3 is selected
  3. It would give the error on last option

### Expected behavior

Should not break, line 1040 gives index out of range error. Instead

### Actual behavior

gives error @ line 1040 : 
TypeError: this.form_field.options[item.options_index] is undefined

### Environment

  - **Chosen Version**:
Latest

  - **jQuery or Prototype Version**:
3.1.0
  - **Browser and Version**:
Firefox : latest
  - **OS and Version**:
Mac OSX : latest

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

I'm using the single select without the search bar in angular js using the angular  directive located here : https://github.com/leocaseiro/angular-chosen. Here is HTML : 

`<select chosen="" disable-search="true"  ng-model="selectedDismissalResason" ng-options="dismissalReason for dismissalReason in dismissalReasonList"></select>
`

Have identified the cause, if we dont give a default selected element, the options_index satrt from "1". This causes the code to break at 1040. 

for more info : email usman.shah@yotascale.com

**Comment by MartinDeHaan** [comment]
I've had the same issue.
It's because after the first time you select an option the place-holder option is removed from the original select due to an angular scope digest.
After a few hours of debugging the only real solution I came across was the put a blank option between the select-tags:

<select chosen="" disable-search="true" ng-model="selectedDismissalResason" ng-options="dismissalReason for dismissalReason in dismissalReasonList"><option value=""></option> </select> 

This way the scope digest wont remove it from the list, because it's not part of the model and it will remain after the select-change.

In every example on https://github.com/leocaseiro/angular-chosen there is also a blank option.
That's how I figured it out. And it makes sense.

**Comment by koenpunt** [comment]
@MartinDeHaan is right, the select should always have an empty option for Chosen to function correctly. So this is probably also the case when using it with Angular

**Comment by azarus** [comment]
> @MartinDeHaan is right, the select should always have an empty option for Chosen to function correctly. So this is probably also the case when using it with Angular.

I have the same issue however having an empty option does not resolve the issue. The problem with angular is that if you use ng-model that is undefined the select doesn't set a proper indexing and then runs into errors later on..
