### ISSUE TITLE
Directory tree.

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [harvesthq/chosen#2691]
I propose organize the files like the directory tree below:

 + dis/
   + css/
   + images/
   + js/

This would facilitate the junction of the chosen with other libraries to reduce the amounts of request for a larger project. At the moment this is not possible because the chosen style sheets has dependency file other extensions, which ends up mixing different types of files in the same directory, complicating maintenance.

**Comment by koenpunt** [comment]
@AlvaroLQueiroz where would you like the tree to be like this? 
In the repository this simply isn't applicable because we don't have the compiled js/css in here. 
If you mean at the bower/npm package; that's something we could look into, although I'm still not sure what the problem is you're describing.

**Comment by AlvaroLQueiroz** [comment]
@koenpunt Sorry for the delay in answering. Yes, I mean the npm / bower packages.
