### ISSUE TITLE
Add ability to remove chosen from a "chosenified" select box.

### ISSUE THREAD

**Issue by AdamHess** [harvesthq/chosen#2734]
Unless it's just not well documented, would like to be able to remove the feature from a select box that's been already enhanced.

While the right answer would be to not apply the feature until you need it, I want to reduce the impact of chosen on the dom by selectively disabling and enabling it.  There are also a bevy of other issues that pop up when you try to dynamically show/hide the select box itself (but that's out of scope of this feature request)

**Comment by stof** [comment]
there is a way remove chosen from a select, moving it back to its native state:

with jQuery:

```js
$('#mySelect').chosen('destroy')
```

Prototype

```js
// Store the Chosen instance somewhere at the time you apply chosen
var chosenInstance = new Chosen(document.getElementById('mySelect));

// Later, you can now destroy it
chosenInstance.destroy();
```

The API is simpler for jQuery, because the jQuery plugin (which is wrapping Chosen) already stores the instance in the jQuery state, and so you don't need to store it in your own code. Note that there is no magic here: the jQuery plugin simply does what I described in the case of Prototype.

**Comment by AdamHess** [comment]
@stof 👍 

Maybe it would be worth documenting? (if it isn't already, the documentation is a bit hard to navigate) You know the Aphorism: "explicit is better than implicit"

**Comment by stof** [comment]
feel free to send PRs to improve the documentation

**Comment by tjschuck** [comment]
@AdamHess Documented on the homepage here: [Observing, Updating, and Destroying Chosen](https://harvesthq.github.io/chosen/#change-update-events)
