### ISSUE TITLE
Issue in conjunction with jquery.validate

### ISSUE THREAD

**Issue by mdi** [harvesthq/chosen#283]
The issue is that chosen doesn't seem to be passing an empty value to jquery.validate when attempting to validate a form containing a select with no option selected. So, blank "required" fields aren't being properly picked up by the validation.

Before upgrading to 0.9.5 this was working correctly. I've no idea what changed in chosen to cause this, but if I disable chosen, the validation works properly.

**Comment by markskayff** [comment]
I am going through this right now. And for what I see, it's not about a hidden field now, but jQuery Validate is complaining about an `<input>` field with no name:
![validation-fail](https://user-images.githubusercontent.com/22687247/37055179-ccbdff9c-215f-11e8-98c0-4cef1054cb48.png)
At first I thought it was due to a non-display, but my console is actually complaining about this above first.
