### ISSUE TITLE
Syntax Warning From Uglifyjs When Minifying chosen.jquery.js

### ISSUE THREAD

**Issue by kgrammer** [harvesthq/chosen#2833]
We are running uglifyjs to create a minified version of chosen.jquery.js and uglifyjs is generating the following warning:

**_WARN: Condition left of || always true [/var/www/sources/public/resources/chosen-js/chosen.jquery.js:1034,33]_**

Lines 1033 to 1037 of chosen.jquery.js contain:
```
   Chosen.prototype.search_results_mouseout = function(evt) {
      if ($(evt.target).hasClass("active-result" || $(evt.target).parents('.active-result').first())) {
        return this.result_clear_highlight();
      }
    };
```
Is the closing paren for the .hasClass() function in the wrong place?  In other words, should this have been written as follows?

```
   Chosen.prototype.search_results_mouseout = function(evt) {
      if ($(evt.target).hasClass("active-result") || $(evt.target).parents('.active-result').first()) {
        return this.result_clear_highlight();
      }
    };
```
### Environment

  - **Chosen Version**: 1.7.0
  - **uglify Version**: 2.7.0
  - **jQuery or Prototype Version**: jquery 3.2.1
  - **Browser and Version**: Yarn 0.24.6
  - **OS and Version**: Ubuntu 14.04

**Comment by tjschuck** [comment]
Hm... seems like it to me.

@koenpunt Right?

@kgrammer Thanks for reporting, and if you'd like, feel free to open up a PR!

It looks like the fix is probably to add parens around the argument to `hasClass` on [this line](https://github.com/harvesthq/chosen/blob/8913ff9dcf03449d933ee0c0f0420365b9fd829a/coffee/chosen.jquery.coffee#L302) — from `.hasClass "active-result"` to `.hasClass("active-result")`.  The [corresponding line in the Prototype version](https://github.com/harvesthq/chosen/blob/8913ff9dcf03449d933ee0c0f0420365b9fd829a/coffee/chosen.proto.coffee#L300) already has those parens, and it looks like its compiled version has the correct conditional.

**Comment by koenpunt** [comment]
Looks like it, yes. But it's obviously easy to fix. But did it introduce any bugs? And if not, do we the parent lookup?

**Comment by tjschuck** [comment]
That line was added in [the initial commit of the jQuery version in 2011](https://github.com/harvesthq/chosen/commit/7f6874bfd02e19a0f733fc753b47394f1ae4b5ca) 😂
