### ISSUE TITLE
Organize like every other JS repo in existence.

### ISSUE THREAD

**Issue by trinadin** [harvesthq/chosen#2850]
You know, with a src folder that has the js file. chosen.jquery.js isn't even here. It's nothing but coffeescript. Wth is this?

**Comment by tjschuck** [comment]
This repository is the source code for Chosen.  It is written in CoffeeScript and Sass.

The JavaScript and CSS files are compiled assets, _not_ the source of Chosen.  They're not checked into this repo because they're not a part of the collaborative development of Chosen.  Same reason you don't find compiled binaries in the version control of most compiled projects.

Precompiled versions of Chosen (as JavaScript and CSS files) can be found on [the releases page](https://github.com/harvesthq/chosen/releases) (for standalone download) and in the [chosen-package](https://github.com/harvesthq/chosen-package) repository (for automated usage by things like NPM or Bower).
