### ISSUE TITLE
List jumps to top after select with CMD

### ISSUE THREAD

**Issue by HannesOberreiter** [harvesthq/chosen#2888]
### Tell us how to reproduce this issue.

- https://harvesthq.github.io/chosen/
- use the multi select field
- select one item with the CMD button holding down
- list jumps after selection always to the top

### Expected behavior / Actual behavior

It should not jump to top? I dont know if this was happening in the old version, but I think it would be more user friendly if it wont jump to the top each time.

### Environment

  - 1.8.2 Chosen

  - Chrome, Safari and Firefox latest

  - macOS Sierra

Cheers
Hannes

**Comment by Skeeve** [comment]
Just saw it now: See mine #2890 as well.

**Comment by Skeeve** [comment]
Copying from #2890 - I hope that's what is expected…

Use case: I have a long list of similar looking entries in my options. Sometimes I want to select several of those entries.

So what I do is, I enter a filter and select the first of the entries, having Cmd pressed.

What I get is the entry. But the filter is gone. Additionally the dropdown is positioned at the beginning.

It would be good if at least the filter would be kept. Would the dropdonw remain positioned it would be great.

### Steps to reproduce

How to reproduce this issue on https://harvesthq.github.io/chosen/.

  1. Enter a filter into the Multiple Select of a country (e.g. "g")

  2. select one of the options while holding cmd (or ctrl) (e.g. Guam) 

  3. Filter gets replaced by the selected entry. Options list is repositioned.

### Expected behavior

In the example above "Guam "should still be displayed. The filter should be kept so that you could add Guatemala now.

### Actual behavior

Instead Guam is now a selected country and the option list is unfiltered at the top and you can select United Kingdom or United States ;)

### Environment

  - **Chosen Version - **: 1.8.2

  - **jQuery or Prototype Version - **: jQuery 1.10 here. Don't know which one you have

  - **Browser and Version - **: FireFox 52.01 / Safari 11.0

  - **OS and Version - **: macOS 10.12

**Comment by Skeeve** [comment]
I just had to remove Chosen from my application as the customer didn't like the inability to select a bunch of options at once :(
