### ISSUE TITLE
prism.js - outdated, source-less binary

### ISSUE THREAD

**Issue by onlyjob** [harvesthq/chosen#3005]
[prism.js](https://github.com/harvesthq/chosen/blob/master/public/docsupport/prism.js) hasn't been touched since 2013 even though it is semantically versioned, [well maintained library](https://github.com/PrismJS/prism/releases).

On top of that committed version is lacking source which is a serious breach of open source compliance because effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in [Debian](https://debian.org).  
It is a bad practice to commit binaries to VCS.

Please replace minified `prism.js` with original, uncompressed, up-to-date version.
I recommend using the following URL:

  https://github.com/PrismJS/prism/raw/v1.15.0/prism.js

which I would note into `prism.js.URL` file to document file's origin.

Read more about pre-minified files here https://wiki.debian.org/onlyjob/no-minification

Thanks.

**Comment by koenpunt** [comment]
Not sure what you mean; but the prism.js file contains a license header, so I don't really see a problem there.

**Comment by onlyjob** [comment]
Availability of source code is a foundation of [open source](https://opensource.org/osd-annotated).
Here _prism.js_ is provided only in compiled form, without source so license header is not good enough.

How do you know if _prism.js_ hasn't been tampered with? It is not possible to re-build this file from source because source is missing...

Also it would be nice to update it to current version. Please? ;)

**Comment by koenpunt** [comment]
> Availability of source code is a foundation of open source.

True, and we provide the source code of Chosen. But since we're not the author of Prism, and we're not distributing Prism itself as software, I believe we are free to use a minified version, as long as we mention the author/refer to the license.

> It is not possible to re-build this file from source because source is missing...

Again, since we're not the author of Prism, there's no point in re-building the file. And if we want, we can always go to [the source](https://github.com/PrismJS/prism/), and create a new minified version.

> Also it would be nice to update it to current version. Please? ;)

Feel free to submit a PR! 😃

**Comment by onlyjob** [comment]
No it is not that simple. It is true that license pf Prism allows you to re-distribute binaries.
But it is good practice to distribute all binaries with source.

Your source distribution is incomplete without Prism source and obtaining correct source for this particular binary is not possible: its version is unknown and the librrary is so old that it pre-dates first Priism release. You can get the different version of the source but not for this particular binary.
You wouldn't be able to reproduceibly re-build the exact minifified binary which is committed to the source tree here.

Downstream we have a practical problem with open source compliance. We can't distribute source-less binaries at all. All sources must be included. How much it would affect _chosen_ if Prism is entirely removed? It would at least break the examples but it is entirely avoidable if sources are provided.

I merely ask you to distribute Prism source. It is a small request and it appears to be easy enought to do. Also you can use the opportunity to upgrade very old library to the current version - isn't that enough as incentive of its own?

As for PR, I'll see what I can do but I'd rather trust maintainers of this repo to do necessary transitions...

Thanks.

**Comment by tjschuck** [comment]
@koenpunt This is just a dev/build dependency, and [it's available on NPM](https://www.npmjs.com/package/prismjs).  Should we just include it that way?  Or is that more trouble than it's worth?

**Comment by onlyjob** [comment]
Removing `prism.js` is an option. Either way it should not be (re-)distributed in binary-only form.

Imagine a GNU/Linux distro shipping just binaries, claiming that sources used to build those binaries were once available in the internet... ;)

**Comment by koenpunt** [comment]
> Imagine a GNU/Linux distro shipping just binaries, claiming that sources used to build those binaries were once available in the internet

I'm pretty sure there are binaries distributed in distro's, of which the source is not included. Of course this source is somewhere else available. 

For that reason I think we can simple go with updating prism to a tagged version, and make sure that version is mentioned in the minified source.

Btw; why are you discussing prism, but not jQuery, of which we do not include the source either..

**Comment by tjschuck** [comment]
Hm, also, Prism isn't really a part of the source of Chosen at all — it's strictly for [the Chosen website](https://harvesthq.github.io/chosen/), and has nothing to do with Chosen-as-libary, per se.  It's (correctly) not included in the [pre-built distributions of Chosen](https://github.com/harvesthq/chosen-package), and isn't necessary for anyone to build Chosen from source themselves.

I'm now leaning towards just calling this a non-issue.  We could potentially upgrade our version of Prism, and/or we could include it via NPM instead of vendoring it, but either of those would really be for the purposes of solving some actual problem for us.  There's no OSS/distribution issue.

**Comment by koenpunt** [comment]
> There's no OSS/distribution issue.

That's what I've been thinking too!

**Comment by onlyjob** [comment]
Correction: ZoneMinder incorporated _Chosen_ with both minified and uncompressed jQuery.
Hence source-less jQuery is not currently a problem.

**Comment by koenpunt** [comment]
> Are you became so accustomed to bad practice and abuse of open source principles that it takes so much effort to deal with your denial of the issue?

Being rude is not going to help anyone.

> that the source is somewhere else? Where specifically? See?

If you'd read it correctly, you would know I was not talking about the source of prism, but about the source of certain binaries distributed with distros.

Hence I already suggested updating to a tagged version, to which source we then can refer to, if ever anyone has to.

But as @tjschuck mentioned, you won't be needing prism for the distribution, since it only used for the html docs (that's why it lives in the `docssupport` folder).

**Comment by koenpunt** [comment]
But in terms of functionality I don't see any reason why we should update prism if the current one is working correctly.

**Comment by onlyjob** [comment]
Noted, _prism.js_ is not required for normal functioning of _Chosen_. Thanks.

Updating libraries (even when they are not broken) is a normal dependency higiene - it just has to be done sometimes.
[CHANGELOG](https://github.com/PrismJS/prism/blob/master/CHANGELOG.md) might highlight some reasons for updating. 
Fast forward to pick-up 5+ years of development and 600+ bugs fixed upstream.
What more incentive is needed to update unsupported library to its current version?
You can't even file a bug against that obsolete `prism.js` which is currently used...

**Comment by koenpunt** [comment]
I think we can close this now.

**Comment by onlyjob** [comment]
Closing without action? Should we fix the problem first and perhaps update _prism.js_ before closing the ticket?

Just closing the bug doesn't make the problem go away, you know...

**Comment by tjschuck** [comment]
I'm with @koenpunt — there's no actual problem or issue here.

What's the point of updating prism.js?  It's working fine.  It's a static nice-to-have-but-non-critical visual design dependency of a static website.  We'll update it when it breaks or when we _need_ to update it.  Otherwise, our limited Chosen time is quite frankly better spent on other things.

**Comment by onlyjob** [comment]
It's like saying "why do car mainnenance if it still works?".

Even without technical reasons, this matter is _primarily about open source compliance_.
But I have a feeling that nobody here cares about such things as all I've got so far were excuses why not do anything about it...
