### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by ankitkumarOO7** [harvesthq/chosen#3024]
ankit@snooker MINGW32 /c/xampp/htdocs/housera
$ npm install
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

i am getting this error. pls someone help.

**Comment by stof** [comment]
Are you getting this error when working on chosen itself, or when adding it as a dependency in your own project ?

Chosen does not have any dependency on browserslist (only some dev dependency due to using autoprefixer), so this error is probably not related to chosen if you are using Chosen in your own project.

**Comment by tjschuck** [comment]
@ankitkumarOO7 Those are just warnings and won't cause anything to fail (yet!). We will work on fixing those at some point, but right now, they shouldn't cause any actual issue for you.

For now, just ignore the warnings and rest assured that we know about them — no Chosen functionality should be affected!

See also: #3010
