### ISSUE TITLE
Feature Request: Prevent dropdown from opening unless minimum n characters entered

### ISSUE THREAD

**Issue by SushantRT** [harvesthq/chosen#3068]
Hello,

I went through all the options but couldn't find an option where I could set minimum number of characters so that when someone clicks on search box, it will not open the drop-down unless the threshold is reached.

P.S: I can help in development for this.

**Comment by tjschuck** [comment]
We've historically rejected that kind of "delayed searching until _n_ characters" because of UX issues.  See #2359 and its linked issues.  _However_, if your primary concern is due to performance because of a large number of options, there is an alternative solution: `max_shown_results` introduced in #2362.  It was specifically added "to increase performance of selects with very many options", so this may be what you're after.  More information about `max_shown_results` can be found [in the docs](http://harvesthq.github.io/chosen/options.html).
