### ISSUE TITLE
page up/down don't work in chosen selects

### ISSUE THREAD

**Issue by chrisforbes** [harvesthq/chosen#367]

**Comment by TobbyNgKaHoi** [comment]
Hi @pfiller ,
I know that adding more code is much more easy than removing code, but chosen would benefit from supporting page up/down key, since the search result may still contain more than 50 of items (e.g. taking s as example in the demo page)

without the page up/down, the user are forced to either repeating pressing the up/down key manually to scroll the list (typing speed need to be slow, otherwise the list scroll so fast) or using the mouse to click the scroll bar (which hurts productivity).

I already come up with a much more reliable solution in javascript http://jsfiddle.net/TobbyNgKaHoi/b7759x9v/, which doesn't hard code the number of item to move) , I was hopping someone can translate this script to coffeescirpt equivalent.

**Comment by pfiller** [comment]
Duplicated by #1912. Going to close in favor of that discussion.
