### ISSUE TITLE
minLength option on search

### ISSUE THREAD

**Issue by tzz** [harvesthq/chosen#402]
It would be very nice if we could ask for at least N characters to be typed before triggering the search, for large lists.  I looked through the issues and docs and source, and did not see this addressed.

Thanks!
Ted

**Comment by pfiller** [comment]
I don't think delaying the search makes a lot of sense. The idea with Chosen is to make it easy to navigate large lists. If I want to select "Tanzania" from a list of countries, typing "ta" gets me there fast! 

What is the argument against instant filtering?

**Comment by tjschuck** [comment]
"Performance" is the reason for delaying the search.

We've discussed a "min length" option before, and elected to take an alternate approach: `max_shown_results`.

See #2359 (this same idea) and #2362 (the better, now-merged alternative) for more info.

This approach (waiting to start search until _n_ chars) is not very user friendly, because it seems as though there are no results when you start typing, even though there are and you just need to type more.

**Comment by tjschuck** [comment]
By the way, documentation for `max_shown_results` is on [the options page](http://harvesthq.github.io/chosen/options.html).

**Comment by pfiller** [comment]
Thanks for setting me straight, @tjschuck. I read too many issues this weekend they all blurred together, I guess.
