### ISSUE TITLE
Disabled selectbox's has no effect on Chosen

### ISSUE THREAD

**Issue by xLink** [harvesthq/chosen#67]
Chosen dosent take into account when the selectbox it replaces is disabled.

I am using the prototype version.

**Comment by sri10102005Narayanan** [comment]
Hi..
I am using chosen Version 1.4.2 

On disabled multiselect listbox chosen style has no effect.. All the mentioned code is available in this version as far as I gone through.. 

Can anyone suggest me a better option to make it work.. asap. please

Thanks
Srijith

**Comment by mxmkhv** [comment]
Works for me, as well! Thanks!

**Comment by adamsjohnloan** [comment]
Hello
  This adams john loan we are here to give loans to those who have financial difficulties. Do you need a loan to pay the bills? Or do you want to start a business but do not have the capital at your fingertips? If you need financial assistance to improve their financial status by determining the financial business or family. Do not worry anymore, because we are here to make sure we can help you solve your financial instability and make you financially stable. We offer emergency loans to individuals and families. Including organizations and companies. Contact us now for your loan at an interest rate starting at 2% email; adamsjohnloanfirm@hotmail.com
