### ISSUE TITLE
Feature request: support for nested optgroup

### ISSUE THREAD

**Issue by sahuguet** [harvesthq/chosen#77]
It would be nice to have multiple levels of optgroup.
The current implementation simply ignores the nesting.

regards,

Arnaud

**Comment by DirkReiners** [comment]
Just to add another voice to this: I would really like to see this, too!

@Bakkie123 That's a neat idea, but the problem is that it won't show the groups when you start searching. I only needed to know the top-level group when searching, so I just left the first level optgroup with your approach for the other levels, but a more general solution would definitely be appreciated...
