### ISSUE TITLE
Single select with multiple select style

### ISSUE THREAD

**Issue by wyqydsyq** [harvesthq/chosen#875]
It would be nice to be able to have a single option select box appear like the multiple select ones - that is, the same behaviour except the user can't select more than one option.

This would allow using chosen like an autocomplete text field, which often doesn't meet my requirements as I usually need to have a value (id etc.) associated with the text displayed to the user.

This is pretty low-priority but sure would be a nice addition.

**Comment by pfiller** [comment]
> Issue is solved so I think!

I agree! The workaround is good enough for this one. Single selects look different than multiple selects because they _are_ different.

**Comment by Paytah232** [comment]
This workaround is okay, but I understand where @wyqydsyq is coming from. If you're trying to make your UI a little more seamless, having the drop downs be the same style (but with different hidden functionality) would be a very nice feature.

Example in my website, I think it would be nicer if this particular multiselect (left) would fill the text without the tab notation (so it looks more like the right). The right here (because the styling is different) doesn't look as nice as it doesn't fit in perfectly with the other rows and icons like the left does.

![image](https://user-images.githubusercontent.com/44075588/132450990-e34cab34-ad59-4759-ae4d-454437f30052.png)

@pfiller Chance to reopen this to provide a solution? I would be inclined to think this would be handled by jQuery, i.e. it would be another option to pass for a specific item, example:

![image](https://user-images.githubusercontent.com/44075588/132451150-5029e1ce-d3f6-4bf5-a5b4-6a4eb26d80f8.png)
